### ISSUE TITLE
Introduction and hinting overview

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/how-to-hint-variable-fonts#1]
### TODO

- [x] What hinting is today
- [x] common rendering environments
- [x] problems that hinting solves in current rendering env's
- [x] how hinting has evolved as screens/hardware has improved
